global:
  scrape_interval: 20s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'docker'
    static_configs:
      - targets: ['prometheus:9323']

  - job_name: "application"
    static_configs:
      - targets: ["prometheus:8081"]
      - targets: ["prometheus:8082"]
